### PR TITLE
readme: add corepc and archive rust-bitcoind-json-*

### PR DESCRIPTION
**Pull request by storopoli**

### CODE REVIEW

**Comment by storopoli** [comment]
Don't know if you are following this repo, hence here's a friendly ping @tcharding.

**Comment by apoelstra** [comment]
utACK c336a5675fe7e21dd5774af0bbc1440f900a65c3

**Comment by tcharding** [comment]
Nice! While we are at it can you move the `rust-bitcoin-json-*` crates to the archived section please.

**Review by tcharding — APPROVED** [review]
ACK 663854089e5af0673f9ece2c81745eb2df58c239

Thanks man.

**Comment by apoelstra** [comment]
LGTM

**Pull request merged**
